# Generated by Django 5.2 on 2025-06-04 10:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='studentt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter your name', max_length=200)),
                ('number', models.CharField(help_text='Enter your student number', max_length=20, unique=True)),
                ('major', models.CharField(help_text='Enter your major', max_length=50)),
                ('year', models.CharField(help_text='Enter your year', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter your name', max_length=200)),
                ('department', models.CharField(help_text='Enter your departmnet', max_length=200)),
                ('email', models.EmailField(help_text='Enter your email', max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='profiles/')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='student.studentt')),
            ],
        ),
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter course name', max_length=50)),
                ('credit', models.PositiveSmallIntegerField()),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='enrollments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Completed', 'Completed'), ('Withdrawn', 'Withdrawn')], default='Active', max_length=20)),
                ('enrollment_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.studentt')),
            ],
            options={
                'unique_together': {('student', 'course')},
            },
        ),
    ]
