# Generated by Django 5.2 on 2025-06-05 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_profiles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiles',
            name='user',
        ),
        migrations.AddField(
            model_name='profiles',
            name='student',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.studentt'),
        ),
        migrations.DeleteModel(
            name='profile',
        ),
    ]
