# Generated by Django 5.2 on 2025-06-05 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_studentt_user_alter_profiles_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='student.studentt'),
        ),
    ]
