# Generated by Django 5.2 on 2025-06-06 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_alter_studentt_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollments',
            name='grade',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
